// <auto-generated />
namespace MovieDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202108242348349_OrderClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
