// <auto-generated />
namespace MovieDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nullInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullInt));
        
        string IMigrationMetadata.Id
        {
            get { return "202108021858064_nullInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
